[[testkit]]
=== JUnit Platform 検査キット

// The `junit-platform-testkit` artifact provides support for executing a test plan on the
// JUnit Platform and then verifying the expected results. As of JUnit Platform 1.4, this
// support is limited to the execution of a single `TestEngine` (see <<testkit-engine>>).
`junit-platform-testkit` アーティファクトは、JUnit Platform でテスト計画を実行し、テスト結果と期待結果を検証するための機能を提供します。
ただし、JUnit Platform 1.4 から単独のテスト実行エンジン（<<testkit-engine>> を参照）による実行しかできなくなりました。

[[testkit-engine]]
==== テスト実行エンジン検査キット

// The `{testkit-engine-package}` package provides support for executing a `{TestPlan}` for a
// given `{TestEngine}` running on the JUnit Platform and then accessing the results via a
// fluent API to verify the expected results. The key entry point into this API is the
// `{EngineTestKit}` which provides static factory methods named `engine()` and `execute()`.
// It is recommended that you select one of the `engine()` variants to benefit from the
// fluent API for building a `LauncherDiscoveryRequest`.
`{testkit-engine-package}` パッケージは、JUnit Platform で実行した `{TestEngine}` のテスト結果を期待結果と検証するためのフルーエント API を提供します。
主なエントリポイントは `{EngineTestKit}` クラスの `static` メソッド `engine()` と `execute()` です。
`LauncherDiscoveryRequest` を作成するフルーエント API の利点を活用して、柔軟に `engine()` を選択することをお勧めします。

// NOTE: If you prefer to use the `LauncherDiscoveryRequestBuilder` from the `Launcher` API
// to build your `LauncherDiscoveryRequest`, you must use one of the `execute()` variants in
// `EngineTestKit`.
NOTE: Launcher API の `LauncherDiscoveryRequestBuilder` で `LauncherDiscoveryRequest` を作成するなら、`EngineTestKit` の `execute()` メソッドを使用してください。

// The following test class written using JUnit Jupiter will be used in subsequent examples.
以降のコード例では次のテストクラスを使用します。

[[testkit-engine-ExampleTestCase]]
[source,java,indent=0]
----
include::{testDir}/example/ExampleTestCase.java[tags=user_guide]
----

// For the sake of brevity, the following sections demonstrate how to test JUnit's own
// `JupiterTestEngine` whose unique engine ID is `"junit-jupiter"`. If you want to test your
// own `TestEngine` implementation, you need to use its unique engine ID. Alternatively, you
// may test your own `TestEngine` by supplying an instance of it to the
// `EngineTestKit.engine(TestEngine)` static factory method.
説明を簡略化するため、以降のセクションではエンジン ID が `"junit-jupiter"` である JUnit 本体の `JupiterTestEngnine` を使用します。
独自の `TestEngine` を試したければ、エンジン ID を変更するか、`EngineTestKit.engine(TestEngine)` メソッドを使ってください。

[[testkit-engine-statistics]]
==== 統計情報を確認する

// One of the most common features of the Test Kit is the ability to assert statistics
// against events fired during the execution of a `TestPlan`. The following tests demonstrate
// how to assert statistics for _containers_ and _tests_ in the JUnit Jupiter `TestEngine`.
// For details on what statistics are available, consult the Javadoc for `{EventStatistics}`.
検査キットで最もよく使われる機能の1つが、`TestPlan` を実行している間に発生したイベントの統計情報を確認する機能です。
次のコード例では、Junit Jupiter のテスト実行エンジンが処理した _テストコンテナ_ と _テスト_ に関する統計情報を確認しています。
利用できる統計情報について詳しくは `{EventStatistics}` の Javadoc を参照してください。

[source,java,indent=0]
----
include::{testDir}/example/testkit/EngineTestKitStatisticsDemo.java[tags=user_guide]
----
// <1> Select the JUnit Jupiter `TestEngine`.
// <2> Select the <<testkit-engine-ExampleTestCase, `ExampleTestCase`>> test class.
// <3> Execute the `TestPlan`.
// <4> Filter by _container_ events.
// <5> Assert statistics for _container_ events.
// <6> Filter by _test_ events.
// <7> Assert statistics for _test_ events.
<1> テスト実行エンジンを指定する
<2> テストクラスとして <<testkit-engine-ExampleTestCase, `ExampleTestCase`>> を指定する
<3> `TestPlan` を実行する
<4> _テストコンテナ_ のイベントを選択する
<5> _テストコンテナ_ のイベントに関する統計情報を確認する
<6> _テスト_ のイベントを選択する
<7> _テスト_ のイベントに関する統計情報を確認する

// NOTE: In the `verifyJupiterContainerStats()` test method, the counts for the `started` and
// `succeeded` statistics are `2` since the `JupiterTestEngine` and the
// <<testkit-engine-ExampleTestCase, `ExampleTestCase`>> class are both considered containers.
NOTE: `verifyJupiterContainerStats()` では、`JupiterTestEngine` と <<testkit-engine-ExampleTestCase, `ExampleTestCase`>> の両方が認識しているテストコンテナについて、`started` と `succeeded` イベントが `2` 回発生していることを確認しています。

[[testkit-engine-events]]
==== イベントを確認する

// If you find that <<testkit-engine-statistics, asserting statistics>> alone is insufficient
// for verifying the expected behavior of test execution, you can work directly with the
// recorded `{Event}` elements and perform assertions against them.
<<testkit-engine-statistics, 統計情報を確認する>> だけでは、テスト実行時に期待する振る舞いを検証するのに不足しているなら、記録された `{Event}` そのものを直接的に確認できます。

// For example, if you want to verify the reason that the `skippedTest()` method in
// <<testkit-engine-ExampleTestCase, `ExampleTestCase`>> was skipped, you can do that as
// follows.
例えば、<<testkit-engine-ExampleTestCase, `ExampleTestCase`>> の `skippedTest()` をスキップした理由を確認するには、次のように記述します。

[TIP]
====
// The `assertThatEvents()` method in the following example is a shortcut for
// `org.assertj.core.api.Assertions.assertThat(events.list())` from the {AssertJ} assertion
// library.
以降のコード例における `assertThatEvents()` は `{AssertJ}` の提供する `org.assertj.core.api.Assertions.assertThat(events.list())` に対するショートカットです。

// For details on what _conditions_ are available for use with AssertJ assertions against
// events, consult the Javadoc for `{EventConditions}`.
使用している _条件_ について詳しくは `{EventConditions}` の Javadoc を参照してください。
====

[source,java,indent=0]
----
include::{testDir}/example/testkit/EngineTestKitSkippedMethodDemo.java[tags=user_guide]
----
// <1> Select the JUnit Jupiter `TestEngine`.
// <2> Select the `skippedTest()` method in the <<testkit-engine-ExampleTestCase,
//     `ExampleTestCase`>> test class.
// <3> Execute the `TestPlan`.
// <4> Filter by _test_ events.
// <5> Save the _test_ `Events` to a local variable.
// <6> Optionally assert the expected statistics.
// <7> Assert that the recorded _test_ events contain exactly one skipped test named
//     `skippedTest` with `"for demonstration purposes"` as the _reason_.
<1> テスト実行エンジンを指定する
<2> テストクラス <<testkit-engine-ExampleTestCase, `ExampleTestCase`>> の `skippedTest()` を指定する
<3> `TestPlan` を実行する
<4> _テスト_ のイベントを選択する
<5> _テスト_ のイベントをローカル変数に保存する
<6> ついでにイベントの統計情報を確認する
<7> 記録した _テスト_ イベントに、`"for demonstration purposes"` というメッセージを含むイベントが1つだけ存在し、`skippedTest()` メソッドをスキップしたことを確認する

// If you want to verify the type of exception thrown from the `failingTest()` method in
// <<testkit-engine-ExampleTestCase, `ExampleTestCase`>>, you can do that as follows.
`failingTest()` メソッドのスローした例外クラスを確認するときは、次のように記述します。

[TIP]
====
// For details on what _conditions_ are available for use with AssertJ assertions against
// events and execution results, consult the Javadoc for `{EventConditions}` and
// `{TestExecutionResultConditions}`, respectively.
使用している _条件_ について詳しくは `{EventConditions}` と `{TestExecutionResultConditions}` の Javadoc を参照してください。
====

[source,java,indent=0]
----
include::{testDir}/example/testkit/EngineTestKitFailedMethodDemo.java[tags=user_guide]
----
// <1> Select the JUnit Jupiter `TestEngine`.
// <2> Select the <<testkit-engine-ExampleTestCase, `ExampleTestCase`>> test class.
// <3> Execute the `TestPlan`.
// <4> Filter by _test_ events.
// <5> Assert that the recorded _test_ events contain exactly one failing test named
//     `failingTest` with an exception of type `ArithmeticException` and an error message
//     equal to `"/ by zero"`.
<1> テスト実行エンジンを指定する
<2> テストクラスとして <<testkit-engine-ExampleTestCase, `ExampleTestCase`>> を指定する
<3> `TestPlan` を実行する
<4> _テスト_ のイベントを選択する
<5> 記録した _テスト_ イベントに、`"/ by zero"` というメッセージを含む `ArithmeticException` をスローしたイベントが1つだけ存在し、`failingTest()` メソッドが失敗したことを確認する

// Although typically unnecessary, there are times when you need to verify **all** of the
// events fired during the execution of a `TestPlan`. The following test demonstrates how to
// achieve this via the `assertEventsMatchExactly()` method in the `EngineTestKit` API.
普通なら不要ですが、`TestPlan` を実行している間に発生した **全ての** イベントを確認しなければならない場合があるかもしれません。
次のコード例では `EngineTestKit` API の `assertEventsMatchExactly()` メソッドでそのようなことをしています。

[TIP]
====
// Since `assertEventsMatchExactly()` matches conditions exactly in the order in which the
// events were fired, <<testkit-engine-ExampleTestCase, `ExampleTestCase`>> has been
// annotated with `@TestMethodOrder(OrderAnnotation.class)` and each test method has been
// annotated with `@Order(...)`. This allows us to enforce the order in which the test
// methods are executed, which in turn allows our `verifyAllJupiterEvents()` test to be
// reliable.
`assertEventsMatchExactly()` はイベントが発生したのと同じ順番で条件と比較していきます。
<<testkit-engine-ExampleTestCase, `ExampleTestCase`>> は `@TestMethodOrder(OrderAnnotation.class)` で修飾しているし、それぞれのテストメソッドは `@Order(...)` で修飾しているので、常に同じ順番で実行されます。
したがって、`verifyAllJupiterEvents()` の結果は（順序の違いに）影響されません。
====

// If you want to do a _partial_ match _with_ or _without_ ordering requirements, you can use
// the methods `assertEventsMatchLooselyInOrder()` and `assertEventsMatchLoosely()`,
// respectively.
順序を無視して _部分的に_ 比較したければ、`assertEventsMatchLooselyInOrder()` や `assertEventsMatchLoosely()` を使うといいでしょう。

[source,java,indent=0]
----
include::{testDir}/example/testkit/EngineTestKitAllEventsDemo.java[tags=user_guide]
----
// <1> Select the JUnit Jupiter `TestEngine`.
// <2> Select the <<testkit-engine-ExampleTestCase, `ExampleTestCase`>> test class.
// <3> Execute the `TestPlan`.
// <4> Filter by _all_ events.
// <5> Print all events to the supplied `writer` for debugging purposes. Debug information
//     can also be written to an `OutputStream` such as `System.out` or `System.err`.
// <6> Assert _all_ events in exactly the order in which they were fired by the test engine.
<1> テスト実行エンジンを指定する
<2> テストクラスとして <<testkit-engine-ExampleTestCase, `ExampleTestCase`>> を指定する
<3> `TestPlan` を実行する
<4> _テスト_ のイベントを選択する
<5> デバッグ用に全てのイベントを `writer` へ出力する（`System.out` や `System.err` のような `OutputStream` に出力することもできます）
<6> テストエンジンの発生した _全ての_ イベントが想定した順序になっているか確認する

// The `debug()` invocation from the preceding example results in output similar to the
// following.
前のコード例に登場する `debug()` は次のような出力をするでしょう。

[source,options="nowrap"]
----
All Events:
	Event [type = STARTED, testDescriptor = JupiterEngineDescriptor: [engine:junit-jupiter], timestamp = 2018-12-14T12:45:14.082280Z, payload = null]
	Event [type = STARTED, testDescriptor = ClassTestDescriptor: [engine:junit-jupiter]/[class:example.ExampleTestCase], timestamp = 2018-12-14T12:45:14.089339Z, payload = null]
	Event [type = SKIPPED, testDescriptor = TestMethodTestDescriptor: [engine:junit-jupiter]/[class:example.ExampleTestCase]/[method:skippedTest()], timestamp = 2018-12-14T12:45:14.094314Z, payload = 'for demonstration purposes']
	Event [type = STARTED, testDescriptor = TestMethodTestDescriptor: [engine:junit-jupiter]/[class:example.ExampleTestCase]/[method:succeedingTest()], timestamp = 2018-12-14T12:45:14.095182Z, payload = null]
	Event [type = FINISHED, testDescriptor = TestMethodTestDescriptor: [engine:junit-jupiter]/[class:example.ExampleTestCase]/[method:succeedingTest()], timestamp = 2018-12-14T12:45:14.104922Z, payload = TestExecutionResult [status = SUCCESSFUL, throwable = null]]
	Event [type = STARTED, testDescriptor = TestMethodTestDescriptor: [engine:junit-jupiter]/[class:example.ExampleTestCase]/[method:abortedTest()], timestamp = 2018-12-14T12:45:14.106121Z, payload = null]
	Event [type = FINISHED, testDescriptor = TestMethodTestDescriptor: [engine:junit-jupiter]/[class:example.ExampleTestCase]/[method:abortedTest()], timestamp = 2018-12-14T12:45:14.109956Z, payload = TestExecutionResult [status = ABORTED, throwable = org.opentest4j.TestAbortedException: Assumption failed: abc does not contain Z]]
	Event [type = STARTED, testDescriptor = TestMethodTestDescriptor: [engine:junit-jupiter]/[class:example.ExampleTestCase]/[method:failingTest()], timestamp = 2018-12-14T12:45:14.110680Z, payload = null]
	Event [type = FINISHED, testDescriptor = TestMethodTestDescriptor: [engine:junit-jupiter]/[class:example.ExampleTestCase]/[method:failingTest()], timestamp = 2018-12-14T12:45:14.111217Z, payload = TestExecutionResult [status = FAILED, throwable = java.lang.ArithmeticException: / by zero]]
	Event [type = FINISHED, testDescriptor = ClassTestDescriptor: [engine:junit-jupiter]/[class:example.ExampleTestCase], timestamp = 2018-12-14T12:45:14.113731Z, payload = TestExecutionResult [status = SUCCESSFUL, throwable = null]]
	Event [type = FINISHED, testDescriptor = JupiterEngineDescriptor: [engine:junit-jupiter], timestamp = 2018-12-14T12:45:14.113806Z, payload = TestExecutionResult [status = SUCCESSFUL, throwable = null]]
----
